name: Run tests and release

on: push

jobs:
  test:
    uses: csm10495/actions/.github/workflows/pytest.yml@master
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "3.11"]'
      # by default, operating-systems points to ubuntu/mac/windows
  pdoc3:
    needs: test
    if: github.event_name != 'pull_request' # && github.ref == 'refs/heads/master'
    uses: csm10495/actions/.github/workflows/pdoc3.yml@master
    with:
      python-version: '3.11'
      operating-system: 'ubuntu-latest'
  markdown-autodocs:
    needs: pdoc3
    if: github.event_name != 'pull_request' # && github.ref == 'refs/heads/master'
    uses: csm10495/actions/.github/workflows/markdown-autodocs.yml@master
    with:
      python-version: '3.11'
      operating-system: 'ubuntu-latest'
      cmd-to-run: 'pyhtcc --help > help_output.txt'
      file-to-update: README.md
