name: Run tests and release

on: push

jobs:
  test:
    uses: csm10495/actions/.github/workflows/pytest.yml@master
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "3.11"]'
      # by default, operating-systems points to ubuntu/mac/windows
  pdoc3:
    uses: csm10495/actions/.github/workflows/pdoc3.yml@master
    with:
      python-version: '3.11'
      operating-system: 'ubuntu-latest'
